"""The docs site: generated tool reference is current, and the pages hang together."""

from __future__ import annotations

import difflib
import importlib.util
import re
import unicodedata
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
DOCS = REPO / "docs"
TOOLS_DIR = DOCS / "tools"
STEMS = ("model", "report")


def _load_generator():
    spec = importlib.util.spec_from_file_location(
        "gen_tool_reference", REPO / "scripts" / "gen_tool_reference.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


@pytest.fixture(scope="module")
def gen():
    return _load_generator()


def _lf(data: bytes) -> str:
    return data.decode("utf-8").replace("\r\n", "\n")


# --- the generated reference ------------------------------------------------------

def test_committed_tool_reference_is_up_to_date(gen, tmp_path):
    try:
        written = gen.write_all(tmp_path)
    except ImportError as exc:
        pytest.skip(f"a server could not be imported: {exc}")
    assert sorted(p.name for p in written) == [f"{s}.md" for s in STEMS]
    for path in written:
        committed = TOOLS_DIR / path.name
        assert committed.exists(), (
            f"docs/tools/{path.name} is missing. Run: "
            "python scripts/gen_tool_reference.py")
        fresh, current = _lf(path.read_bytes()), _lf(committed.read_bytes())
        if fresh != current:
            diff = "\n".join(list(difflib.unified_diff(
                current.splitlines(), fresh.splitlines(),
                "committed", "regenerated", lineterm=""))[:40])
            pytest.fail(f"docs/tools/{path.name} is stale. Run: "
                        f"python scripts/gen_tool_reference.py\n{diff}")


def test_every_registered_tool_has_a_heading(gen):
    try:
        for spec in gen.SERVERS:
            tools = gen.load_tools(spec["module"])
            page = _lf((TOOLS_DIR / f"{spec['stem']}.md").read_bytes())
            headings = set(re.findall(r"^### `(pbi_[a-z0-9_]+)`$", page, re.M))
            assert headings == {t["name"] for t in tools}, spec["stem"]
    except ImportError as exc:
        pytest.skip(f"a server could not be imported: {exc}")


def test_generated_pages_are_lf_utf8_without_bom():
    for stem in STEMS:
        data = (TOOLS_DIR / f"{stem}.md").read_bytes()
        assert not data.startswith(b"\xef\xbb\xbf")
        assert b"\r" not in data
        assert data.endswith(b"\n") and not data.endswith(b"\n\n")
        assert data.decode("utf-8").startswith("<!-- Generated by")


def test_generation_is_deterministic(gen):
    try:
        assert gen.generate() == gen.generate()
    except ImportError as exc:
        pytest.skip(f"a server could not be imported: {exc}")


def test_check_mode_passes_on_the_committed_files(gen, capsys):
    try:
        assert gen.main(["--check"]) == 0
    except ImportError as exc:
        pytest.skip(f"a server could not be imported: {exc}")
    assert "up to date" in capsys.readouterr().out


def test_check_mode_flags_stale_files(gen, tmp_path, capsys):
    try:
        gen.write_all(tmp_path)
    except ImportError as exc:
        pytest.skip(f"a server could not be imported: {exc}")
    assert gen.main(["--check", "--out", str(tmp_path)]) == 0
    (tmp_path / "model.md").write_text("stale\n", encoding="utf-8")
    (tmp_path / "report.md").unlink()
    assert gen.main(["--check", "--out", str(tmp_path)]) == 1
    err = capsys.readouterr().err
    assert "model.md" in err and "report.md" in err


# --- generator pieces ----------------------------------------------------------------

@pytest.mark.parametrize("schema, expected", [
    ({"type": "string"}, "string"),
    ({"anyOf": [{"type": "string"}, {"type": "null"}]}, "string"),
    ({"anyOf": [{"type": "integer"}, {"type": "string"}, {"type": "null"}]},
     "integer or string"),
    ({"type": "array", "items": {"type": "object"}}, "array of object"),
    ({"type": "array", "items": {}}, "array"),
    ({"anyOf": [{"items": {}, "type": "array"}, {"type": "null"}]}, "array"),
    ({"type": "object", "additionalProperties": True}, "object"),
    ({"enum": ["light", "dark"]}, 'one of "light", "dark"'),
    ({"$ref": "#/$defs/Position"}, "Position"),
    ({"type": ["integer", "null"]}, "integer"),
    ({}, "any"),
])
def test_type_rendering(gen, schema, expected):
    assert gen.type_of(schema) == expected


def test_access_hints_are_read_across_mcp_spellings(gen):
    class Ann:
        pass

    class Tool:
        name = "pbi_x"
        description = "Does x."
        inputSchema = {"properties": {}, "required": []}

    camel, snake = Ann(), Ann()
    camel.readOnlyHint, camel.destructiveHint, camel.idempotentHint = False, True, False
    snake.read_only_hint, snake.destructive_hint, snake.idempotent_hint = True, False, True
    a, b = Tool(), Tool()
    a.annotations, b.annotations = camel, snake
    da, db = gen.describe_tool(a), gen.describe_tool(b)
    assert (da["read_only"], da["destructive"], da["idempotent"]) == (False, True, False)
    assert (db["read_only"], db["destructive"], db["idempotent"]) == (True, False, True)
    assert gen._access(da) == "**Write** · destructive"
    assert gen._access(db) == "**Read-only** · idempotent"

    class Bare(Tool):
        annotations = None
        input_schema = {"properties": {}}
        inputSchema = None

    assert gen.describe_tool(Bare())["read_only"] is False


def test_parameters_come_from_the_input_schema(gen):
    class Tool:
        name = "pbi_demo"
        description = "  Demo tool.\n    Second line."
        annotations = None
        inputSchema = {
            "properties": {
                "table": {"type": "string", "title": "Table"},
                "limit": {"anyOf": [{"type": "integer"}, {"type": "null"}],
                          "default": 20},
                "mode": {"type": "string", "default": "fast",
                         "description": "How | fast"},
                "flag": {"type": "boolean", "default": False},
            },
            "required": ["table"],
        }

    tool = gen.describe_tool(Tool())
    assert tool["description"] == "Demo tool.\nSecond line."
    assert [(p["name"], p["type"], p["required"], p["default"])
            for p in tool["params"]] == [
        ("table", "string", True, ""),
        ("limit", "integer", False, "20"),
        ("mode", "string", False, '"fast"'),
        ("flag", "boolean", False, "false"),
    ]
    md = gen.render_tool(tool)
    assert "| `table` | string | yes |  |" in md
    assert "| `limit` | integer | no | `20` |" in md
    assert "Description |" in md and "How \\| fast" in md   # pipes escaped in cells


def test_descriptions_are_identical_whatever_the_python_docstring_handling(gen):
    """<= 3.12 keeps docstring indentation, >= 3.13 strips it at compile time.

    The dry-run note core.tooling appends is unindented, so a naive
    inspect.cleandoc leaves the older interpreters' indentation in place and
    the committed reference would differ per Python version.
    """
    from core.tooling import DRY_RUN_DOC

    class Tool:
        name = "pbi_x"
        annotations = None
        inputSchema = {"properties": {}}

        def __init__(self, description):
            self.description = description

    py312 = "Does x.\n    Second line.\n    Third line." + DRY_RUN_DOC
    py313 = "Does x.\nSecond line.\nThird line." + DRY_RUN_DOC
    expected = "Does x.\nSecond line.\nThird line." + DRY_RUN_DOC
    assert gen.describe_tool(Tool(py312))["description"] == expected
    assert gen.describe_tool(Tool(py313))["description"] == expected
    # tools without the appended note (reads, own-dry-run writes) are unchanged
    assert gen.describe_tool(Tool("Does x.\n    More."))["description"] == "Does x.\nMore."
    assert gen.describe_tool(Tool(""))["description"] == ""


def test_prose_wraps_tool_names_and_escapes_html(gen):
    text = "Use pbi_undo after `pbi_keep` and <b>this</b>; see pbi_list_backups."
    out = gen._prose(text)
    assert out == ("Use `pbi_undo` after `pbi_keep` and &lt;b>this&lt;/b>; "
                   "see `pbi_list_backups`.")


def test_tools_are_grouped_by_area_with_a_fallback(gen):
    assert gen.area_of("model", "pbi_create_measure") == "Measures"
    assert gen.area_of("model", "pbi_list_measures") == "Reading the model"
    assert gen.area_of("model", "pbi_undo") == "Undo, transactions and backups"
    assert gen.area_of("report", "pbi_build_page") == "Building pages"
    assert gen.area_of("report", "pbi_add_filter") == "Filters"
    assert gen.area_of("report", "pbi_restore_visual") == \
        "Undo, transactions and recovery"
    assert gen.area_of("report", "pbi_lint_page") == "Validation and lint"
    assert gen.area_of("report", "pbi_frobnicate") == "Other tools"
    assert gen.area_of("model", "pbi_frobnicate") == "Other tools"


def test_unknown_tools_still_get_listed():
    gen = _load_generator()
    page = gen.render_page(
        gen.SERVERS[0],
        [{"name": "pbi_brand_new", "description": "New thing.", "read_only": True,
          "destructive": False, "idempotent": False, "params": []}])
    assert "## Other tools" in page and "### `pbi_brand_new`" in page
    assert "**1 tool** (1 read-only, 0 write)" in page


# --- the hand-written pages -------------------------------------------------------------

def _nav_files() -> list[str]:
    text = (REPO / "mkdocs.yml").read_text(encoding="utf-8")
    block = re.search(r"^nav:\n((?:[ \t]+.*\n|\n)+)", text, re.M)
    assert block, "mkdocs.yml has no nav"
    return re.findall(r"([\w./-]+\.md)\b", block.group(1))


def test_nav_lists_only_existing_pages_and_every_page_is_in_the_nav():
    listed = set(_nav_files())
    assert len(listed) >= 10
    for rel in listed:
        assert (DOCS / rel).is_file(), f"nav points at missing docs/{rel}"
    on_disk = {p.relative_to(DOCS).as_posix() for p in DOCS.rglob("*.md")}
    assert on_disk == listed, f"pages not in nav: {sorted(on_disk - listed)}"


def _slug(heading: str) -> str:
    """Python-Markdown's toc slugify, as mkdocs uses for heading anchors."""
    text = re.sub(r"[`*]", "", heading)
    text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode()
    text = re.sub(r"[^\w\s-]", "", text).strip().lower()
    return re.sub(r"[-\s]+", "-", text)


def _anchors(path: Path) -> set[str]:
    out, seen = set(), {}
    in_fence = False
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("```"):
            in_fence = not in_fence
        m = None if in_fence else re.match(r"#{1,6}\s+(.*?)\s*#*\s*$", line)
        if not m:
            continue
        slug = _slug(m.group(1))
        n = seen.get(slug, 0)
        seen[slug] = n + 1
        out.add(slug if n == 0 else f"{slug}_{n}")
    return out


def test_internal_links_resolve():
    link = re.compile(r"\]\(([^)\s]+)\)")
    problems = []
    for page in DOCS.rglob("*.md"):
        text = page.read_text(encoding="utf-8")
        text = re.sub(r"```.*?```", "", text, flags=re.S)
        for target in link.findall(text):
            if re.match(r"[a-z][a-z0-9+.-]*:", target) or target.startswith("#"):
                if target.startswith("#") and target[1:] not in _anchors(page):
                    problems.append(f"{page.name}: unknown anchor {target}")
                continue
            path, _, anchor = target.partition("#")
            dest = (page.parent / path).resolve()
            if not dest.is_file():
                problems.append(f"{page.relative_to(DOCS)}: {target} -> missing file")
            elif anchor and anchor not in _anchors(dest):
                problems.append(f"{page.relative_to(DOCS)}: {target} -> unknown anchor")
    assert not problems, "\n".join(problems)


def test_docs_never_hard_code_counts_that_go_stale():
    """Tool and test totals live in the README + generated pages only."""
    for page in DOCS.glob("*.md"):
        text = page.read_text(encoding="utf-8")
        assert not re.search(r"\b\d+ tools\b", text), page.name
        assert not re.search(r"\b\d+ tests\b", text), page.name


def test_hand_written_pages_are_lf_utf8_without_bom():
    for page in DOCS.rglob("*.md"):
        data = page.read_bytes()
        assert not data.startswith(b"\xef\xbb\xbf"), page
        assert b"\r" not in data, page
        data.decode("utf-8")


def test_cookbook_and_pages_name_only_real_tools():
    """Every `pbi_*` mentioned in prose must be a registered tool."""
    import asyncio

    try:
        import model_server.server as model
        import report_server.server as report
    except ImportError as exc:
        pytest.skip(f"a server could not be imported: {exc}")
    known = set()
    for mod in (model, report):
        known |= {t.name for t in asyncio.run(mod.mcp.list_tools())}
    bad = {}
    for page in DOCS.glob("*.md"):
        text = page.read_text(encoding="utf-8")
        if page.name == "development.md":       # its code fences use example names
            text = re.sub(r"```.*?```", "", text, flags=re.S)
        names = set(re.findall(r"\bpbi_[a-z0-9_]+\b", text))
        # a trailing underscore is a wildcard like pbi_* or pbi_service_
        unknown = {n for n in names if n not in known and not n.endswith("_")}
        # the optional cloud server's tools are documented generically
        if page.name == "cloud.md":
            unknown = set()
        if unknown:
            bad[page.name] = sorted(unknown)
    assert not bad, bad
