"""Generate the MCP tool reference pages for the docs site.

Imports each server, lists its registered tools exactly as an MCP client
would (``list_tools``) and renders one Markdown page per server:

    docs/tools/model.md     the pbi-model server
    docs/tools/report.md    the pbi-report server

Each tool gets its access hints (read-only / destructive / idempotent, read
across the mcp 1.x camelCase and 2.x snake_case spellings), a parameter table
(type, required, default) taken from the input schema, and its description.
Tools are grouped into areas by name; anything unrecognised lands in
"Other tools", so new tool modules never need a change here to be listed.

    python scripts/gen_tool_reference.py            # rewrite docs/tools/*.md
    python scripts/gen_tool_reference.py --check    # exit 1 if they are stale
    python scripts/gen_tool_reference.py --out DIR  # write somewhere else

The output is identical under mcp 1.x and 2.x. tests/test_docs_reference.py
fails when the committed pages are stale.
"""

from __future__ import annotations

import argparse
import asyncio
import importlib
import inspect
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DEFAULT_OUT = REPO / "docs" / "tools"

if str(REPO) not in sys.path:      # `core` and the servers import from the repo
    sys.path.insert(0, str(REPO))

BANNER = ("<!-- Generated by scripts/gen_tool_reference.py from the live "
          "servers. Do not edit by hand; run the script instead. -->")

# --- areas: first matching rule wins; patterns are full-matched against the
# tool name without its "pbi_" prefix ----------------------------------------

_PROJECT = ["set_project", "doctor"]
_UNDO = ["undo", "undo_history", "begin_transaction", "commit", "rollback",
         r".*backup.*", r".*trash.*", r"restore_.*"]

AREAS: dict[str, list[tuple[str, list[str]]]] = {
    "model": [
        ("Project and diagnostics", _PROJECT),
        ("Reading the model", ["get_model", "list_measures",
                               "model_lineage"]),
        ("Measures", [r".*measure.*"]),
        ("Columns, relationships and calculation groups",
         [r".*(column|relationship|calc_group).*"]),
        ("Undo, transactions and backups", _UNDO),
    ],
    "report": [
        ("Project and diagnostics",
         _PROJECT + ["capabilities", "project_summary", "project_diff"]),
        ("Undo, transactions and recovery", _UNDO),
        ("Validation and lint", [r"validate_.*", r"lint_.*"]),
        ("Autopilot and analysis", [r"scaffold_.*", "profile_model",
                                    "model_usage"]),
        ("Building pages", [r"build_.*", "create_page", "duplicate_page"]),
        ("Pages", [r".*_pages?", "page_style", "set_page_role"]),
        ("Visuals", [r".*_visual(s|_raw|_interactions)?", "update_bindings",
                     "move_visual", "format_visual", "sort_visual"]),
        ("Design elements", ["add_text", "add_image", "add_shape"]),
        ("Themes", [r".*theme.*"]),
        ("Filters", [r".*filter.*"]),
        ("Navigation and bookmarks", ["add_nav_button", r".*bookmark.*"]),
    ],
    "service": [
        ("Session and sign-in", ["service_status", "service_login", "set_project"]),
        ("Workspaces and items", ["list_workspaces", "list_items",
                                  "get_item_definition"]),
        ("Publish", ["publish_project"]),
        ("Refresh", [r".*refresh.*"]),
        ("Deployment pipelines", [r".*pipeline.*"]),
        ("Export", ["export_report"]),
    ],
}
OTHER_AREA = "Other tools"

SERVERS = (
    {
        "stem": "model",
        "module": "model_server.server",
        "server": "pbi-model",
        "title": "Model server tools",
        "intro": (
            "The `pbi-model` server reads and edits the **semantic model** "
            "(TMDL) of a Power BI Project: measures, columns, relationships, "
            "calculation groups and DAX lineage. Edits are surgical text "
            "changes, so partitions, annotations and M source survive "
            "byte for byte. Call `pbi_set_project(path)` first."),
    },
    {
        "stem": "report",
        "module": "report_server.server",
        "server": "pbi-report",
        "title": "Report server tools",
        "intro": (
            "The `pbi-report` server builds and edits the **report** (PBIR) "
            "of a Power BI Project: pages, visuals, formatting, themes, "
            "filters and design elements. Every report write is validated "
            "against the official Fabric schemas before it reaches disk. "
            "Call `pbi_set_project(path)` first, then `pbi_capabilities()` "
            "to learn the visual types, buckets and filters."),
    },
    {
        "stem": "service",
        "module": "service_server.server",
        "server": "pbi-service",
        "title": "Service server tools (optional)",
        "intro": (
            "The optional `pbi-service` server talks to the Power BI and "
            "Fabric REST APIs: publish a local project, refresh, deploy and "
            "export. The local servers never import it. Cloud actions "
            "cannot be previewed with `dry_run` and are not journaled."),
    },
)

LEGEND = """\
## How to read this page

- **Read-only** tools never change the project. **Write** tools do.
- **Destructive** marks tools that delete or overwrite content, so hosts can
  ask before running them. **Idempotent** means repeating the call with the
  same arguments changes nothing further.
- Write tools that edit project files accept `dry_run=true`: the operation
  runs on a scratch copy and returns the unified diff, and nothing is
  written. Every real write is journaled and can be reverted with
  `pbi_undo`. Do not use `dry_run` with the restore tools that take a path
  into the project. See [Safety](../safety.md#dry-run).
- Types are JSON Schema types. A parameter is **required** when it has no
  default.
"""


# --- reading tools the way a client sees them ---------------------------------

_HINT_FIELDS = {
    "readOnlyHint": "read_only_hint",
    "destructiveHint": "destructive_hint",
    "idempotentHint": "idempotent_hint",
}


def _hint(tool, hint: str) -> bool:
    """One annotation hint across mcp 1.x (camelCase) and 2.x (snake_case)."""
    ann = tool.annotations
    if ann is None:
        return False
    value = getattr(ann, hint, None)
    if value is None:
        value = getattr(ann, _HINT_FIELDS[hint], None)
    return bool(value)


def _input_schema(tool) -> dict:
    return (getattr(tool, "inputSchema", None)
            or getattr(tool, "input_schema", None) or {})


def type_of(schema) -> str:
    """Compact human type for a JSON Schema fragment."""
    if not isinstance(schema, dict) or not schema:
        return "any"
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    variants = schema.get("anyOf") or schema.get("oneOf")
    if variants:
        parts: list[str] = []
        for variant in variants:
            t = type_of(variant)
            if t != "null" and t not in parts:
                parts.append(t)
        return " or ".join(parts) or "null"
    if "enum" in schema:
        return "one of " + ", ".join(json.dumps(v) for v in schema["enum"])
    t = schema.get("type")
    if isinstance(t, list):
        return " or ".join(x for x in t if x != "null") or "null"
    if t == "array":
        items = schema.get("items")
        return f"array of {type_of(items)}" if items else "array"
    return t or "any"


def clean_description(text: str) -> str:
    """A tool description with indentation normalised, on every Python.

    Python 3.13 strips docstring indentation at compile time, earlier versions
    keep it. core.tooling appends an unindented dry-run note to write tools,
    which defeats inspect.cleandoc's common-margin detection on those older
    versions. So the author's text and the appended note are cleaned apart;
    the output is then identical whichever interpreter generated it.
    """
    from core.tooling import DRY_RUN_DOC

    note = ""
    if text.endswith(DRY_RUN_DOC):
        text, note = text[:-len(DRY_RUN_DOC)], DRY_RUN_DOC
    return inspect.cleandoc(text) + note


def describe_tool(tool) -> dict:
    schema = _input_schema(tool)
    required = set(schema.get("required", []))
    params = []
    for name, prop in (schema.get("properties") or {}).items():
        params.append({
            "name": name,
            "type": type_of(prop),
            "required": name in required,
            "default": (json.dumps(prop["default"])
                        if "default" in prop else ""),
            "description": (prop.get("description") or "").strip(),
        })
    return {
        "name": tool.name,
        "description": clean_description(tool.description or ""),
        "read_only": _hint(tool, "readOnlyHint"),
        "destructive": _hint(tool, "destructiveHint"),
        "idempotent": _hint(tool, "idempotentHint"),
        "params": params,
    }


def load_tools(module: str) -> list[dict]:
    """Import a server module and describe every registered tool."""
    if str(REPO) not in sys.path:
        sys.path.insert(0, str(REPO))
    mod = importlib.import_module(module)
    tools = asyncio.run(mod.mcp.list_tools())
    return sorted((describe_tool(t) for t in tools), key=lambda d: d["name"])


# --- rendering ---------------------------------------------------------------

_CODE_SPAN = re.compile(r"(`[^`]*`)")
_TOOL_NAME = re.compile(r"\bpbi_[a-z0-9_]+\b")


def _prose(text: str) -> str:
    """Markdown-safe prose: tool names become code, raw '<' is escaped."""
    out = []
    for i, part in enumerate(_CODE_SPAN.split(text)):
        if i % 2:                      # inside a code span: leave alone
            out.append(part)
            continue
        part = part.replace("<", "&lt;")
        out.append(_TOOL_NAME.sub(lambda m: f"`{m.group(0)}`", part))
    return "".join(out)


def area_of(stem: str, tool_name: str) -> str:
    short = tool_name[len("pbi_"):] if tool_name.startswith("pbi_") \
        else tool_name
    for area, patterns in AREAS[stem]:
        if any(re.fullmatch(p, short) for p in patterns):
            return area
    return OTHER_AREA


def _access(tool: dict) -> str:
    parts = ["**Read-only**" if tool["read_only"] else "**Write**"]
    if tool["destructive"]:
        parts.append("destructive")
    if tool["idempotent"]:
        parts.append("idempotent")
    return " · ".join(parts)


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def render_tool(tool: dict) -> str:
    lines = [f"### `{tool['name']}`", "", _access(tool), ""]
    if tool["description"]:
        lines += [_prose(tool["description"]), ""]
    if not tool["params"]:
        lines += ["_No parameters._", ""]
        return "\n".join(lines)
    with_desc = any(p["description"] for p in tool["params"])
    header = "| Parameter | Type | Required | Default |"
    rule = "|---|---|---|---|"
    if with_desc:
        header += " Description |"
        rule += "---|"
    lines += [header, rule]
    for p in tool["params"]:
        row = (f"| `{p['name']}` | {_cell(p['type'])} | "
               f"{'yes' if p['required'] else 'no'} | "
               f"{('`' + _cell(p['default']) + '`') if p['default'] else ''} |")
        if with_desc:
            row += f" {_cell(_prose(p['description']))} |"
        lines.append(row)
    lines.append("")
    return "\n".join(lines)


def render_page(spec: dict, tools: list[dict]) -> str:
    stem = spec["stem"]
    grouped: dict[str, list[dict]] = {}
    for tool in tools:
        grouped.setdefault(area_of(stem, tool["name"]), []).append(tool)
    order = [a for a, _ in AREAS[stem] if a in grouped]
    if OTHER_AREA in grouped:
        order.append(OTHER_AREA)

    writes = sum(1 for t in tools if not t["read_only"])
    noun = "tool" if len(tools) == 1 else "tools"
    lines = [
        BANNER, "",
        f"# {spec['title']}", "",
        spec["intro"], "",
        f"**{len(tools)} {noun}** ({len(tools) - writes} read-only, "
        f"{writes} write).", "",
        LEGEND,
    ]
    for area in order:
        lines += [f"## {area}", ""]
        for tool in sorted(grouped[area], key=lambda t: t["name"]):
            lines.append(render_tool(tool))
    return "\n".join(lines).rstrip("\n") + "\n"


def generate() -> dict[str, str]:
    """{file name: page text} for every server."""
    return {f"{spec['stem']}.md": render_page(spec, load_tools(spec["module"]))
            for spec in SERVERS}


def write_all(out_dir: Path) -> list[Path]:
    """Write the pages (LF, UTF-8, no BOM) and return the paths."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for name, text in generate().items():
        path = out_dir / name
        path.write_bytes(text.encode("utf-8"))
        written.append(path)
    return written


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT,
                    help=f"output directory (default: {DEFAULT_OUT})")
    ap.add_argument("--check", action="store_true",
                    help="do not write; exit 1 if the pages are stale")
    args = ap.parse_args(argv)

    if args.check:
        stale = []
        for name, text in generate().items():
            path = args.out / name
            current = (path.read_bytes().decode("utf-8").replace("\r\n", "\n")
                       if path.exists() else None)
            if current != text:
                stale.append(name)
        if stale:
            print("stale tool reference: " + ", ".join(stale) +
                  "\nrun: python scripts/gen_tool_reference.py",
                  file=sys.stderr)
            return 1
        print("tool reference is up to date")
        return 0

    for path in write_all(args.out):
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
